package algebraic.manipulator.read;

public enum Token {EOF, LESS, GREAT, LPAR, RPAR, LSQR, RSQR, LCURL, RCURL, VBAR, DOT, COMMA, COLON, SEMI, EQUAL, SLASH, BACKSLASH, DASH, PLUS, ARROW, STRING, INT}
